apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
  namespace: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      containers:
        - name: openwebui
          image: ghcr.io/open-webui/open-webui:main
          env:
            - name: OLLAMA_API
              value: http://ollama-service.ollama.svc.cluster.local:11434
            - name: WEBUI_USERNAME
              value: admin
            - name: WEBUI_PASSWORD
              value: Darient123
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: openwebui-service
  namespace: openwebui
spec:
  selector:
    app: openwebui
  ports:
    - port: 80
      targetPort: 8080
